# Generated by Django 4.1.2 on 2022-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkwapp', '0003_conections_delete_age_delete_gender_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conections',
            name='person_one_id',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='conections',
            name='person_two_id',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
