# Generated by Django 4.1.2 on 2022-12-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkwapp', '0004_customuser_last_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conections',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='conections',
            name='person_one_id',
        ),
        migrations.RemoveField(
            model_name='conections',
            name='person_two_id',
        ),
    ]
