# Generated by Django 4.1.2 on 2022-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkwapp', '0005_remove_conections_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conections',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conections',
            name='person_one_id',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='conections',
            name='person_two_id',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
